apiVersion: v1
kind: Service
metadata:
  name: s3proxy-internal-lb
  namespace: s3proxy-e2e
  labels:
    app: s3proxy
  annotations:
    networking.gke.io/load-balancer-type: Internal
    cloud.google.com/neg: '{"exposed_ports": {"80": {}}}'
    cloud.google.com/backend-config: '{"default":"s3proxy-backendconfig"}'
spec:
  type: LoadBalancer
  selector:
    app: s3proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
